### ISSUE TITLE
Compilation error in provided xsl files

### ISSUE THREAD

**Issue by kv-v** [schxslt/schxslt#214]
I'm trying to validate xml against Schematrin file in java and getting this error:

```
Type error at char 0 in expression in xsl:sequence/@select on line 54 column 63 of functions.xsl:
  XTTE0780  An empty sequence is not allowed as the result of a call to schxslt:active-patterns#2
at template schxslt:compile on line 38 of compile-2.0.xsl:
     invoked by xsl:call-template at jar:file:/.m2/repository/name/dmaus/schxslt/schxslt/1.7.2/schxslt-1.7.2.jar!/xslt/2.0/compile/compile-2.0.xsl#33
  In template rule with match="/sch:schema" on line 32 of compile-2.0.xsl
     invoked by built-in template rule (text-only)

name.dmaus.schxslt.SchematronException: Error compiling Schematron to transformation stylesheet

	at name.dmaus.schxslt.Compiler.compile(Compiler.java:96)
```

I use empty maven project with jdk8 and only name.dmaus.schxslt.java 3.0 dependency.
There is the same error when I use just name.dmaus.schxslt.schxslt 1.8.2 and create Saxon transformers myself. So it looks like problem is in xsl files provided in jar.

**Comment by dmj** [comment]
Thanks for reporting! Judging from the error message there seem to be no sch:pattern elements in the Schema. Can you provide the Schematron that causes this error? You can send the Schematron to dmaus@dmaus.name if confidentiality is required.

**Comment by kv-v** [comment]
Here is the schema:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<sch:schema xmlns:sch="http://purl.oclc.org/dsdl/schematron"
            xmlns:xs="http://www.w3.org/2001/XMLSchema"
            queryBinding="xslt2">
   <sch:pattern xmlns:sql="urn:schemas-microsoft-com:mapping-schema"
                xmlns:sch="http://www.unisoftware.ru/schematron-extensions"
                name="Обязательность ОГРНИП при первых 4 символах ИННФЛ отличных от 9909">
      <sch:rule context="НПФЛ">
         <!-- 3. Контроль обязательности ОГРНИП при первых 4 символах ИННФЛ отличных от 9909  -->
         <sch:assert test=" ((substring(@ИННФЛ,1,4)!='9909') and @ОГРНИП) or ((substring(@ИННФЛ,1,4)='9909') and @ОГРНИП ) or ((substring(@ИННФЛ,1,4)='9909') and not(@ОГРНИП)) ">
            message
         </sch:assert>
      </sch:rule>
   </sch:pattern>
   <sch:diagnostics/>
</sch:schema>

```

**Comment by dmj** [comment]
I see. The problem is with your Schematron:

```
<sch:pattern xmlns:sql="urn:schemas-microsoft-com:mapping-schema"
                xmlns:sch="http://www.unisoftware.ru/schematron-extensions"
                name="Обязательность ОГРНИП при первых 4 символах ИННФЛ отличных от 9909">
      <sch:rule context="НПФЛ">
         <!-- 3. Контроль обязательности ОГРНИП при первых 4 символах ИННФЛ отличных от 9909  -->
         <sch:assert test=" ((substring(@ИННФЛ,1,4)!='9909') and @ОГРНИП) or ((substring(@ИННФЛ,1,4)='9909') and @ОГРНИП ) or ((substring(@ИННФЛ,1,4)='9909') and not(@ОГРНИП)) ">
            message
         </sch:assert>
      </sch:rule>
```

You redeclare the prefix sch: to 'http://www.unisoftware.ru/schematron-extensions'. That's why SchXslt does not find a valid Schematron pattern. It is looking for sch:pattern elements where the prefix sch: is declared to be 'http://purl.oclc.org/dsdl/schematron'.

This modified Schematron should work:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<sch:schema xmlns:sch="http://purl.oclc.org/dsdl/schematron"
            xmlns:xs="http://www.w3.org/2001/XMLSchema"
            queryBinding="xslt2">
   <sch:pattern xmlns:sql="urn:schemas-microsoft-com:mapping-schema"
                name="Обязательность ОГРНИП при первых 4 символах ИННФЛ отличных от 9909">
      <sch:rule context="НПФЛ">
         <!-- 3. Контроль обязательности ОГРНИП при первых 4 символах ИННФЛ отличных от 9909  -->
         <sch:assert test=" ((substring(@ИННФЛ,1,4)!='9909') and @ОГРНИП) or ((substring(@ИННФЛ,1,4)='9909') and @ОГРНИП ) or ((substring(@ИННФЛ,1,4)='9909') and not(@ОГРНИП)) ">
            message
         </sch:assert>
      </sch:rule>
   </sch:pattern>
   <sch:diagnostics/>
</sch:schema>
```
